In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import scipy.stats as stats
%pip install -q statsmodels
import statsmodels.api as sm
import sklearn as skl

Note: you may need to restart the kernel to use updated packages.

In [4]:
#read all files into pandas dataframes
campaign_data = pd.read_csv('campaign_desc.csv')
campaign_table = pd.read_csv('campaign_table.csv')
causal_data = pd.read_csv('causal_data.csv')
coupon_redemption = pd.read_csv('coupon_redempt.csv')
coupon_table = pd.read_csv('coupon.csv')
hh_demographic = pd.read_csv('hh_demographic.csv')
product = pd.read_csv('product.csv')
transaction_data = pd.read_csv('transaction_data.csv')

In [6]:
#explore campaign data
campaign_data.info()
campaign_data.head(n=5)

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DESCRIPTION  30 non-null     str
 1   CAMPAIGN     30 non-null     int64
 2   START_DAY    30 non-null     int64
 3   END_DAY      30 non-null     int64
dtypes: int64(3), str(1)
memory usage: 1.1 KB

  DESCRIPTION  CAMPAIGN  START_DAY  END_DAY
0       TypeB        24        659      719
1       TypeC        15        547      708
2       TypeB        25        659      691
3       TypeC        20        615      685
4       TypeB        23        646      684

In [8]:
#explore campaign_table data
campaign_table.info()
campaign_table.head(n=5)

<class 'pandas.DataFrame'>
RangeIndex: 7208 entries, 0 to 7207
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   DESCRIPTION    7208 non-null   str
 1   household_key  7208 non-null   int64
 2   CAMPAIGN       7208 non-null   int64
dtypes: int64(2), str(1)
memory usage: 169.1 KB

  DESCRIPTION  household_key  CAMPAIGN
0       TypeA             17        26
1       TypeA             27        26
2       TypeA            212        26
3       TypeA            208        26
4       TypeA            192        26

In [12]:
#explore causal data
causal_data.info()
causal_data.sort_values(by='WEEK_NO', ascending=True).head(n=5)

<class 'pandas.DataFrame'>
RangeIndex: 36786524 entries, 0 to 36786523
Data columns (total 5 columns):
 #   Column      Dtype
---  ------      -----
 0   PRODUCT_ID  int64
 1   STORE_ID    int64
 2   WEEK_NO     int64
 3   display     str
 4   mailer      str
dtypes: int64(3), str(2)
memory usage: 1.4 GB

          PRODUCT_ID  STORE_ID  WEEK_NO display mailer
398197         36413       403        9       1      0
4413866       669453       339        9       0      A
5323711       825616       333        9       7      0
12736400     1027829       363        9       0      A
11110195      983665       292        9       6      0

In [14]:
# explore coupon redemption data
coupon_redemption.info()
coupon_redemption.sort_values(by='DAY', ascending=True).head(n=5)

<class 'pandas.DataFrame'>
RangeIndex: 2318 entries, 0 to 2317
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   household_key  2318 non-null   int64
 1   DAY            2318 non-null   int64
 2   COUPON_UPC     2318 non-null   int64
 3   CAMPAIGN       2318 non-null   int64
dtypes: int64(4)
memory usage: 72.6 KB

      household_key  DAY   COUPON_UPC  CAMPAIGN
2007           2280  225  57008510075        26
1987           2240  226  53600000001        26
716             788  227  51111076635        26
717             788  227  55100055008        26
718             788  227  57218020076        26

In [15]:
#explore coupon table data
coupon_table.info()
coupon_table.head(n=5)

<class 'pandas.DataFrame'>
RangeIndex: 124548 entries, 0 to 124547
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   COUPON_UPC  124548 non-null  int64
 1   PRODUCT_ID  124548 non-null  int64
 2   CAMPAIGN    124548 non-null  int64
dtypes: int64(3)
memory usage: 2.9 MB

    COUPON_UPC  PRODUCT_ID  CAMPAIGN
0  10000089061       27160         4
1  10000089064       27754         9
2  10000089073       28897        12
3  51800009050       28919        28
4  52100000076       28929        25

In [16]:
#explore hh_demographic data
hh_demographic.info()
hh_demographic.head(n=5)

<class 'pandas.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   AGE_DESC             801 non-null    str
 1   MARITAL_STATUS_CODE  801 non-null    str
 2   INCOME_DESC          801 non-null    str
 3   HOMEOWNER_DESC       801 non-null    str
 4   HH_COMP_DESC         801 non-null    str
 5   HOUSEHOLD_SIZE_DESC  801 non-null    str
 6   KID_CATEGORY_DESC    801 non-null    str
 7   household_key        801 non-null    int64
dtypes: int64(1), str(7)
memory usage: 50.2 KB

,AGE_DESC,MARITAL_STATUS_CODE,INCOME_DESC,HOMEOWNER_DESC,HH_COMP_DESC,HOUSEHOLD_SIZE_DESC,KID_CATEGORY_DESC,household_key
0,65+,A,35-49K,Homeowner,2 Adults No Kids,2,None/Unknown,1
1,45-54,A,50-74K,Homeowner,2 Adults No Kids,2,None/Unknown,7
2,25-34,U,25-34K,Unknown,2 Adults Kids,3,1,8
3,25-34,U,75-99K,Homeowner,2 Adults Kids,4,2,13
4,45-54,B,50-74K,Homeowner,Single Female,1,None/Unknown,16

In [17]:
#explore product data
product.info()
product.head(n=5)

<class 'pandas.DataFrame'>
RangeIndex: 92353 entries, 0 to 92352
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   PRODUCT_ID            92353 non-null  int64
 1   MANUFACTURER          92353 non-null  int64
 2   DEPARTMENT            92353 non-null  str
 3   BRAND                 92353 non-null  str
 4   COMMODITY_DESC        92353 non-null  str
 5   SUB_COMMODITY_DESC    92353 non-null  str
 6   CURR_SIZE_OF_PRODUCT  92353 non-null  str
dtypes: int64(2), str(5)
memory usage: 4.9 MB

,PRODUCT_ID,MANUFACTURER,DEPARTMENT,BRAND,COMMODITY_DESC,SUB_COMMODITY_DESC,CURR_SIZE_OF_PRODUCT
0,25671,2,GROCERY,National,FRZN ICE,ICE - CRUSHED/CUBED,22 LB
1,26081,2,MISC. TRANS.,National,NO COMMODITY DESCRIPTION,NO SUBCOMMODITY DESCRIPTION,
2,26093,69,PASTRY,Private,BREAD,BREAD:ITALIAN/FRENCH,
3,26190,69,GROCERY,Private,FRUIT - SHELF STABLE,APPLE SAUCE,50 OZ
4,26355,69,GROCERY,Private,COOKIES/CONES,SPECIALTY COOKIES,14 OZ

In [18]:
#explore transaction data
transaction_data.info()
transaction_data.head(n=5)

<class 'pandas.DataFrame'>
RangeIndex: 2595732 entries, 0 to 2595731
Data columns (total 12 columns):
 #   Column             Dtype
---  ------             -----
 0   household_key      int64
 1   BASKET_ID          int64
 2   DAY                int64
 3   PRODUCT_ID         int64
 4   QUANTITY           int64
 5   SALES_VALUE        float64
 6   STORE_ID           int64
 7   RETAIL_DISC        float64
 8   TRANS_TIME         int64
 9   WEEK_NO            int64
 10  COUPON_DISC        float64
 11  COUPON_MATCH_DISC  float64
dtypes: float64(4), int64(8)
memory usage: 237.6 MB

,household_key,BASKET_ID,DAY,PRODUCT_ID,QUANTITY,SALES_VALUE,STORE_ID,RETAIL_DISC,TRANS_TIME,WEEK_NO,COUPON_DISC,COUPON_MATCH_DISC
0,2375,26984851472,1,1004906,1,1.39,364,-0.60,1631,1,0.0,0.0
1,2375,26984851472,1,1033142,1,0.82,364,0.00,1631,1,0.0,0.0
2,2375,26984851472,1,1036325,1,0.99,364,-0.30,1631,1,0.0,0.0
3,2375,26984851472,1,1082185,1,1.21,364,0.00,1631,1,0.0,0.0
4,2375,26984851472,1,8160430,1,1.50,364,-0.39,1631,1,0.0,0.0